import { useContext } from "react";
import { TripContext } from "../context/TripContext";
import ReactMarkdown from "react-markdown";
import { getOverview } from "../utils/aiParser";
import { FaGlobe, FaCompass, FaCalendarDay, FaInfoCircle, FaHotel, FaUtensils, FaCamera, FaCalendarAlt } from "react-icons/fa";

function AIOverview({ loading, aiResult }) {
  const { tripPlan } = useContext(TripContext);

  if (loading) {
    return (
      <div className="bg-white p-8 rounded-2xl shadow-lg flex flex-col items-center justify-center min-h-[350px] mt-8">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        <h3 className="mt-6 text-xl font-bold text-gray-700 animate-pulse">
          Analyzing destination details...
        </h3>
      </div>
    );
  }

  // If structured trip plan is loaded, render a high-fidelity visual dashboard!
  if (tripPlan) {
    const attractions = tripPlan.attractions || [];
    const bestTime = tripPlan.bestTimeToVisit || "Not resolved";
    const hotelsCount = tripPlan.hotels?.length || 0;
    const restCount = tripPlan.restaurants?.length || 0;
    const festivalCount = tripPlan.festivals?.length || 0;
    const photoCount = tripPlan.photoSpots?.length || 0;

    return (
      <div className="mt-8 max-w-5xl mx-auto space-y-8">
        
        {/* Page title */}
        <div className="border-b border-gray-100 pb-4">
          <h2 className="text-3xl font-extrabold text-blue-700 flex items-center gap-3">
            <FaGlobe className="text-blue-500" /> AI Travel Overview
          </h2>
          <p className="text-gray-500 text-xs mt-1">
            General highlights, season ratings, and top landmarks generated by VoyageAI.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Left Column (2/3) - Overview & Attractions */}
          <div className="lg:col-span-2 space-y-6">
            
            {/* Overview description */}
            <div className="relative overflow-hidden rounded-[28px] border border-white/60 bg-gradient-to-br from-sky-50/90 via-white/95 to-indigo-100/80 p-6 shadow-[0_20px_60px_rgba(59,130,246,0.14)] backdrop-blur-md space-y-4">
              <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_left,_rgba(96,165,250,0.22),_transparent_35%),radial-gradient(circle_at_bottom_right,_rgba(129,140,248,0.2),_transparent_28%)]" />
              <div className="relative z-10 flex items-center justify-between gap-3">
                <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                  <span className="inline-flex h-9 w-9 items-center justify-center rounded-full bg-blue-100 text-blue-600">
                    <FaInfoCircle />
                  </span>
                  Destination Highlights
                </h3>
                <span className="rounded-full bg-gradient-to-r from-blue-600 to-indigo-600 px-3 py-1 text-[10px] font-bold uppercase tracking-[0.18em] text-white shadow-sm">
                  AI Summary
                </span>
              </div>

              <div className="relative z-10 rounded-[22px] bg-white/85 border border-sky-100/90 p-4 text-slate-700 shadow-[inset_0_1px_0_rgba(255,255,255,0.9)]">
                <ReactMarkdown
                  components={{
                    p: ({ children }) => (
                      <p className="text-sm leading-7 text-slate-700 mb-3 last:mb-0">{children}</p>
                    ),
                    ul: ({ children }) => (
                      <ul className="space-y-2 text-sm text-slate-700 pl-5 list-disc">{children}</ul>
                    ),
                    ol: ({ children }) => (
                      <ol className="space-y-2 text-sm text-slate-700 pl-5 list-decimal">{children}</ol>
                    ),
                    li: ({ children }) => (
                      <li className="leading-6">{children}</li>
                    ),
                    strong: ({ children }) => (
                      <strong className="font-bold text-slate-900">{children}</strong>
                    ),
                    em: ({ children }) => (
                      <em className="text-blue-700 not-italic">{children}</em>
                    ),
                    h1: ({ children }) => (
                      <h1 className="text-xl font-extrabold text-slate-900 mb-3">{children}</h1>
                    ),
                    h2: ({ children }) => (
                      <h2 className="text-base font-bold text-sky-700 mt-4 mb-2">{children}</h2>
                    ),
                    h3: ({ children }) => (
                      <h3 className="text-sm font-bold text-slate-800 mt-3 mb-2">{children}</h3>
                    ),
                  }}
                >
                  {tripPlan.overview || ""}
                </ReactMarkdown>
              </div>
            </div>

            {/* Attractions */}
            {attractions.length > 0 && (
              <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100 space-y-4">
                <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
                  <FaCompass className="text-blue-500" /> Top Attractions to See
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {attractions.map((item, idx) => (
                    <div
                      key={idx}
                      className="p-4 bg-gray-50 rounded-xl border border-gray-100 hover:bg-blue-50/20 transition-all"
                    >
                      <h4 className="font-bold text-gray-800 text-sm">{item.name}</h4>
                      <p className="text-gray-500 text-[11px] mt-1 leading-normal">
                        {item.description}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>

          {/* Right Column (1/3) - Best Time & Stats */}
          <div className="space-y-6">
            
            {/* Best Time Card */}
            <div className="bg-gradient-to-br from-amber-400 via-amber-500 to-orange-500 text-white rounded-3xl p-6 shadow-md border border-amber-300">
              <h3 className="text-lg font-bold flex items-center gap-2">
                <FaCalendarDay /> Season Peak
              </h3>
              <p className="text-sm font-semibold mt-3 leading-relaxed text-amber-50">
                {bestTime}
              </p>
            </div>

            {/* General Trip Stats */}
            <div className="bg-white border border-gray-100 rounded-3xl p-6 shadow-md space-y-5">
              <h3 className="text-base font-bold text-gray-800 border-b border-gray-50 pb-3">
                📋 Compilation Summary
              </h3>

              <div className="space-y-4">
                <div className="flex justify-between items-center text-xs">
                  <span className="text-gray-500 flex items-center gap-2"><FaHotel /> Stays Recommended</span>
                  <span className="font-bold text-gray-800">{hotelsCount} Stays</span>
                </div>
                
                <div className="flex justify-between items-center text-xs">
                  <span className="text-gray-500 flex items-center gap-2"><FaUtensils /> Restaurants Listed</span>
                  <span className="font-bold text-gray-800">{restCount} Spots</span>
                </div>

                <div className="flex justify-between items-center text-xs">
                  <span className="text-gray-500 flex items-center gap-2"><FaCalendarAlt /> Local Festivals</span>
                  <span className="font-bold text-gray-800">{festivalCount} Events</span>
                </div>

                <div className="flex justify-between items-center text-xs">
                  <span className="text-gray-500 flex items-center gap-2"><FaCamera /> Photo Spots</span>
                  <span className="font-bold text-gray-800">{photoCount} Spots</span>
                </div>
              </div>
            </div>

          </div>

        </div>

      </div>
    );
  }

  // Fallback to ReactMarkdown if structured JSON is not populated yet
  return (
    <div className="bg-white rounded-2xl shadow-lg p-6 mt-8 max-w-4xl mx-auto">
      <h2 className="text-3xl font-bold text-blue-700 mb-5">
        🌍 AI Travel Overview
      </h2>

      <ReactMarkdown
        components={{
          h1: ({ children }) => (
            <h1 className="text-3xl font-bold text-blue-700 mb-4">{children}</h1>
          ),
          h2: ({ children }) => (
            <h2 className="text-2xl font-semibold text-blue-600 mt-5 mb-3">{children}</h2>
          ),
          p: ({ children }) => (
            <p className="text-gray-700 leading-8 mb-3">{children}</p>
          ),
          li: ({ children }) => (
            <li className="ml-6 list-disc mb-2">{children}</li>
          ),
        }}
      >
        {getOverview(aiResult)}
      </ReactMarkdown>
    </div>
  );
}

export default AIOverview;